# Site settings
title: G-Türk İHA
email: gturkiha@gmail.com
url: https://example.github.io
description: "_____"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 # - title: twitter
 #   url: https://twitter.com/
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
  - title: instagram
    url: https://www.instagram.com/gturkiha/
  - title: linkedin
    url: https://www.linkedin.com/company/g-turk-i%CC%87ha

# Build settings
markdown: kramdown
permalink: pretty
